wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 128
BETAS:
  desc: null
  value:
  - 0.9
  - 0.98
EPOCH:
  desc: null
  value: 50
EPS:
  desc: null
  value: 1.0e-06
EVAL_BATCH_SIZE:
  desc: null
  value: 32
EVAL_EVERY:
  desc: null
  value: 50
IMAGE_PATH_TEMPLATE:
  desc: null
  value:
    angel: /raid/xiaoyuz1/sketch_datasets/angel_images_weight_5_all/{}.png
    face: /raid/xiaoyuz1/sketch_datasets/face_images_weight_5_all/{}.png
LR:
  desc: null
  value: 5.0e-06
START_EPOCH:
  desc: null
  value: 0
TEMPLATE:
  desc: null
  value: 0
TEST_CATEGORY:
  desc: null
  value:
  - face
  - angel
TRAIN_CATEGORY:
  desc: null
  value:
  - face
WEIGHT_DECAY:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1650203844
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 14
      4: 3.8.12
      5: 0.12.14
      8:
      - 1
      - 5
default_line_diameter:
  desc: null
  value: 10
line_diameter_scale:
  desc: null
  value:
  - 0.25
  - 1.25
open_clip:
  desc: null
  value: false
rotate:
  desc: null
  value:
  - -45.0
  - 45.0
scale:
  desc: null
  value:
  - 0.75
  - 1.25
trans:
  desc: null
  value:
  - 0.15
  - 0.15
