python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/apple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/apple --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/apple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/apple --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/apple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/apple --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/apple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/apple --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/cactus --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/cactus --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/cactus --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/cactus --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/cactus --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/cactus --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/cactus --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/cactus --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/duck --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/duck --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/duck --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/duck --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/duck --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/duck --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/duck --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/duck --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pineapple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pineapple --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pineapple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pineapple --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pineapple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pineapple --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pineapple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pineapple --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ice_cream --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ice_cream --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ice_cream --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ice_cream --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ice_cream --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ice_cream --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ice_cream --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ice_cream --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/coffee_cup --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/coffee_cup --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/coffee_cup --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/coffee_cup --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/coffee_cup --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/coffee_cup --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/coffee_cup --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/coffee_cup --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/backpack --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/backpack --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/backpack --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/backpack --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/backpack --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/backpack --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/backpack --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/backpack --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/angel --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/angel --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/angel --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/angel --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/angel --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/angel --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/angel --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/angel --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/bulldozer --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/bulldozer --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/bulldozer --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/bulldozer --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/bulldozer --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/bulldozer --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/bulldozer --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/bulldozer --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/alarm_clock --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/alarm_clock --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/alarm_clock --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/alarm_clock --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/alarm_clock --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/alarm_clock --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/alarm_clock --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/alarm_clock --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ambulance --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ambulance --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ambulance --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ambulance --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ambulance --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ambulance --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ambulance --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ambulance --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ant --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ant --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ant --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ant --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ant --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ant --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ant --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/ant --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pig --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pig --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pig --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pig --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pig --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pig --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pig --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/pig --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/campfire --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/campfire --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/campfire --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/campfire --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/campfire --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/campfire --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/campfire --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/campfire --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/calculator --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/calculator --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/calculator --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/calculator --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/calculator --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/calculator --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/calculator --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/calculator --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/flower --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/flower --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/flower --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/flower --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/flower --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/flower --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/flower --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/flower --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/house --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/house --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/house --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/house --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/house --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/house --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/house --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/house --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/suitcase --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/suitcase --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/suitcase --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/suitcase --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/suitcase --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/suitcase --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/suitcase --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/suitcase --start_idx 600 --end_idx 800
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/crab --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/crab --start_idx 0 --end_idx 200
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/crab --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/crab --start_idx 200 --end_idx 400
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/crab --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/crab --start_idx 400 --end_idx 600
python extract_clip_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/crab --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/clip/crab --start_idx 600 --end_idx 800
