python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/candle --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/candle --label candle
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/apple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/apple --label apple
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/cactus --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/cactus --label cactus
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/duck --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/duck --label duck
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pineapple --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/pineapple --label pineapple
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ice_cream --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/ice_cream --label ice_cream
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/coffee_cup --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/coffee_cup --label coffee_cup
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/drill --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/drill --label drill
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/backpack --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/backpack --label backpack
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/angel --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/angel --label angel
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/bulldozer --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/bulldozer --label bulldozer
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/alarm_clock --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/alarm_clock --label alarm_clock
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/face --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/face --label face
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ambulance --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/ambulance --label ambulance
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/ant --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/ant --label ant
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/butterfly --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/butterfly --label butterfly
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/pig --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/pig --label pig
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/campfire --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/campfire --label campfire
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/calculator --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/calculator --label calculator
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/airplane --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/airplane --label airplane
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/basket --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/basket --label basket
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/flower --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/flower --label flower
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/house --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/house --label house
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/suitcase --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/suitcase --label suitcase
python extract_inception_features.py --folder /raid/xiaoyuz1/sketch_datasets/spg/crab --feature_save_folder /raid/xiaoyuz1/sketch_datasets/spg_features/cnn/crab --label crab
